name: Health Check
run-name: Health Check
on:
    schedule:
        - cron: '0/5 * * * *'

jobs:
    health:
        runs-on: ubuntu-latest
        steps:
            - name: Check deployed service URL
              uses: jtalk/url-health-check-action@v4
              with:
                  url: "https://shiloaf.github.io/full-stack-open-pokedex"