name: Deployment pipeline
run-name: "Deployment pipeline"
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: "Install dependencies"
              run: npm install
            - name: "Check style"
              run: npm run eslint
            - name: "Build project"
              run: npm run build
            - name: "Upload pages artifact"
              uses: actions/upload-pages-artifact@v3
              if: always() && github.token != ''
              with:
                path: './dist/full-stack-open-pokedex'
            - name: "Run tests"
              run: npm run test
            - name: "Install Playwright Browsers"
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test

    deploy:
        runs-on: ubuntu-latest
        needs: build_test
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - name: "Deploy to Render"
              if: always() && github.token != ''
              run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
            - name: Deploy to GitHub Pages
              if: always() && github.token != ''
              id: deployment
              uses: actions/deploy-pages@v4